apiVersion: v1
kind: Pod
metadata:
  name: scenario-e-high
  namespace: monitoring
  labels:
    app: scenario-e
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
    ports:
    - containerPort: 80
