apiVersion: v1
kind: Pod
metadata:
  name: scenario-b
  namespace: monitoring
  labels:
    app: scenario-b
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "100Mi"
          cpu: "100m"

    - name: nginx-exporter
      image: nginx/nginx-prometheus-exporter:0.11.0
      args:
        - -nginx.scrape-uri=http://localhost:80/stub_status
      ports:
        - containerPort: 9113
      resources:
        requests:
          memory: "30Mi"
          cpu: "30m"
        limits:
          memory: "60Mi"
          cpu: "60m"

  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-stub-status-conf
