apiVersion: v1
kind: Pod
metadata:
  name: scenario-d-no-sidecar
  namespace: monitoring
  labels:
    app: scenario-d
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
