apiVersion: v1
kind: Pod
metadata:
  name: scenario-d-with-sidecar
  namespace: monitoring
  labels:
    app: scenario-d
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  - name: log-sidecar
    image: busybox
    command: ["sh", "-c", "tail -f /dev/null"]
