apiVersion: v1
kind: Pod
metadata:
  name: scenario-a
  namespace: monitoring
  labels:
    app: scenario-a
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
