apiVersion: v1
kind: Pod
metadata:
  name: scenario-c-no-init
  namespace: monitoring
  labels:
    app: scenario-c
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      command: ["sh", "-c"]
      args:
        - echo "[nginx] Delaying startup by 5s..." && sleep 5 && nginx -g 'daemon off;'
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d

    - name: nginx-exporter
      image: nginx/nginx-prometheus-exporter:0.11.0
      args:
        - -nginx.scrape-uri=http://localhost:80/stub_status
      ports:
        - containerPort: 9113

    - name: fail-container
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          echo "[fail-container] Starting crash loop...";
          while true; do
            echo "Crashing now...";
            sleep 1;
            false;
          done

  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-stub-status-conf
