apiVersion: v1
kind: Pod
metadata:
  name: scenario-e-low
  namespace: monitoring
  labels:
    app: scenario-e
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
    - containerPort: 80
