apiVersion: v1
kind: Pod
metadata:
  name: scenario-a
  namespace: monitoring
  labels:
    app: scenario-a
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
